using System;
using System.Collections.Generic;

namespace B64
{
    public class ClientTaxCodes
    {
        public object Vendor { get; set; }
        public int? ID { get; set; }
        public object IntegrationID { get; set; }
        public object VendorID { get; set; }
        public object Vendor_IntegrationID { get; set; }
        public string Name { get; set; }
        public double? CityRate { get; set; }
        public double? CountyRate { get; set; }
        public double? StateRate { get; set; }
        public bool GroupTwoMultiplicative { get; set; }
        public object City { get; set; }
        public int? CityGroup { get; set; }
        public object County { get; set; }
        public int? CountyGroup { get; set; }
        public object GroupOneName { get; set; }
        public object GroupTwoName { get; set; }
        public int? HandlingTaxableDefault { get; set; }
        public int? MiscTaxableDefault { get; set; }
        public int? OtherGroup { get; set; }
        public double? OtherRate { get; set; }
        public int? ShippingTaxableDefault { get; set; }
        public object State { get; set; }
        public int? StateGroup { get; set; }
        public double? SurtaxLimit { get; set; }
        public double? SurtaxRate { get; set; }
        public string TaxExemptType { get; set; }
        public object Deleted { get; set; }
        public bool Delete { get; set; }
    }

    public class DefaultSalesRepObject
    {
        public object SalesTerritory { get; set; }
        public object User { get; set; }
        public string SalesRepID { get; set; }
        public string ID { get; set; }
        public object IntegrationID { get; set; }
        public string SalesRepCode { get; set; }
        public string RepName { get; set; }
        public object Notes { get; set; }
        public object UserID { get; set; }
        public object LastUpdate { get; set; }
        public DateTime WTSLastUpdate { get; set; }
        public int? Active { get; set; }
        public object SalesTerritoryID { get; set; }
        public object SalesTerritory_IntegrationID { get; set; }
        public object User_IntegrationID { get; set; }
        public bool Delete { get; set; }
    }

    public class Client
    {
        public List<object> ClientNotes { get; set; }
        public ClientTaxCode? ClientTaxCodes { get; set; }
        public object Currency { get; set; }
        public DefaultSalesRepObject DefaultSalesRepObject { get; set; }
        public object DefaultShipAddress { get; set; }
        public object Distributor { get; set; }
        public object SalesTerritory { get; set; }
        public string ClientID { get; set; }
        public string ID { get; set; }
        public string IntegrationID { get; set; }
        public object IntegrationID2 { get; set; }
        public object IntegrationID3 { get; set; }
        public object DefaultShipAddressID { get; set; }
        public object DefaultShipAddress_IntegrationID { get; set; }
        public object SalesTerritoryID { get; set; }
        public object SalesTerritory_IntegrationID { get; set; }
        public object Currency_IntegrationID { get; set; }
        public object ClientTaxCode_IntegrationID { get; set; }
        public object DistributorID { get; set; }
        public object Distributor_IntegrationID { get; set; }
        public string DefaultSalesRep { get; set; }
        public object DefaultSalesRep_IntegrationID { get; set; }
        public bool AutoInvoice { get; set; }
        public bool AutoSendInvoice { get; set; }
        public bool AutoAddNewBrands { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public object BillAddress3 { get; set; }
        public string BillCity { get; set; }
        public string BillCountry { get; set; }
        public string BillCounty { get; set; }
        public string BillFax { get; set; }
        public object BillMobilePhone { get; set; }
        public string BillName { get; set; }
        public string BillPhone { get; set; }
        public string BillState { get; set; }
        public object BillTo { get; set; }
        public string BillZip { get; set; }
        public object ExtraField1 { get; set; }
        public object ExtraField2 { get; set; }
        public object ExtraField3 { get; set; }
        public object ExtraField4 { get; set; }
        public object ExtraField5 { get; set; }
        public object ExtraField6 { get; set; }
        public string ExtraField7 { get; set; }
        public object ExtraField8 { get; set; }
        public object ExtraField9 { get; set; }
        public string ExtraField10 { get; set; }
        public object ExtraField11 { get; set; }
        public object ExtraField12 { get; set; }
        public object ExtraField13 { get; set; }
        public object ExtraField14 { get; set; }
        public object ExtraField15 { get; set; }
        public object ExtraField16 { get; set; }
        public object ExtraField17 { get; set; }
        public object ExtraField18 { get; set; }
        public object ExtraField19 { get; set; }
        public object ExtraField20 { get; set; }
        public object ExtraField21 { get; set; }
        public object ExtraField22 { get; set; }
        public object ExtraField23 { get; set; }
        public object ExtraField24 { get; set; }
        public object ExtraField25 { get; set; }
        public object ExtraFieldLarge { get; set; }
        public int? MarkupType { get; set; }
        public double? MinMarkupPct { get; set; }
        public double? MaxMarkupPct { get; set; }
        public double? MinMarkupAmt { get; set; }
        public double? MaxMarkupAmt { get; set; }
        public bool AllowTwoStepCompanyDiscounts { get; set; }
        public int? AutomaticOrderHold { get; set; }
        public int? AutomaticOrderHoldDuration { get; set; }
        public string ClientName { get; set; }
        public int? ClientTaxCodeID { get; set; }
        public object ClientTerms { get; set; }
        public object Comment { get; set; }
        public object ContactName { get; set; }
        public object CreditBalance { get; set; }
        public int? CreditHold { get; set; }
        public double? CreditLimit { get; set; }
        public object ClientWarranty { get; set; }
        public int? ContractAdjustments { get; set; }
        public object ContractTermsConditions { get; set; }
        public object CreditManagerEmail { get; set; }
        public object CurrencyCode { get; set; }
        public object CurrencyID { get; set; }
        public double? CustomUpcharge { get; set; }
        public int? DealerClientType { get; set; }
        public object DefaultHeldItemDeliveryMethod { get; set; }
        public object DefaultRetentionPct { get; set; }
        public object DropNumber { get; set; }
        public object EligibleForExtendedWarranty { get; set; }
        public object Email { get; set; }
        public bool EnableAutoGenerateSentQuoteXMLFile { get; set; }
        public object ExtraData { get; set; }
        public object Freight { get; set; }
        public object FulfillmentType { get; set; }
        public bool HasCreditLimit { get; set; }
        public int? Installation { get; set; }
        public object IntegrationGroup { get; set; }
        public object InvoiceEDIAssembly { get; set; }
        public object InvoiceEDIClass { get; set; }
        public object InvoiceEDIPath { get; set; }
        public int? InvoiceMethod { get; set; }
        public object ManufacturerWarranty { get; set; }
        public int? NeedsAttention { get; set; }
        public object OrderAckEDIAssembly { get; set; }
        public object OrderAckEDIClass { get; set; }
        public object OrderAckEDIDirectory { get; set; }
        public int? OrderAckType { get; set; }
        public object OrderIntegrationAssembly { get; set; }
        public object OrderIntegrationCaption { get; set; }
        public object OrderIntegrationClass { get; set; }
        public int? PORequired { get; set; }
        public int? PrepayStatus { get; set; }
        public int? ProductionPriority { get; set; }
        public object ProposalTermsConditions { get; set; }
        public double? QuoteClientMarkupSetupChargePct { get; set; }
        public object ReleaseScreensOption { get; set; }
        public int? RequireQuoteVerification { get; set; }
        public object RequiresRetention { get; set; }
        public object RetailExtendedWarranty { get; set; }
        public object RetentionBillDateTimespan { get; set; }
        public object RouteCode { get; set; }
        public object ShipZone { get; set; }
        public int? Status { get; set; }
        public object Tax1 { get; set; }
        public object Tax2 { get; set; }
        public object TaxExempt { get; set; }
        public object TaxID { get; set; }
        public int? TwoStep { get; set; }
        public object UseCustomerListPriceCodes { get; set; }
        public bool UsedForTesting { get; set; }
        public bool UseShipToFax { get; set; }
        public bool Delete { get; set; }
    }

    public class Roots
    {
        public Client Client { get; set; }
        public object ClientTaxCode { get; set; }
        public object DefaultShippingMethod { get; set; }
        public object PayTerm { get; set; }
        public object ShippingBranch { get; set; }
        public string ID { get; set; }
        public object IntegrationID { get; set; }
        public string ClientID { get; set; }
        public object Client_IntegrationID1 { get; set; }
        public object Client_IntegrationID2 { get; set; }
        public object Client_IntegrationID3 { get; set; }
        public object ShippingBranchID { get; set; }
        public object ShippingBranch_IntegrationID { get; set; }
        public object DefaultShippingMethodID { get; set; }
        public object DefaultShippingMethod_IntegrationID { get; set; }
        public object ClientTaxCodeID { get; set; }
        public object ClientTaxCode_IntegrationID { get; set; }
        public object PayTermsID { get; set; }
        public object PayTerms_IntegrationID { get; set; }
        public object TerritoryID { get; set; }
        public object Territory_IntegrationID { get; set; }
        public object Name { get; set; }
        public object Address1 { get; set; }
        public object Address2 { get; set; }
        public object Address3 { get; set; }
        public object City { get; set; }
        public object Country { get; set; }
        public object County { get; set; }
        public object Email { get; set; }
        public object Fax { get; set; }
        public object MobilePhone { get; set; }
        public object Phone { get; set; }
        public object State { get; set; }
        public object Zip { get; set; }
        public object ExtraData { get; set; }
        public object ExtraField1 { get; set; }
        public object ExtraField2 { get; set; }
        public object ExtraField3 { get; set; }
        public object ExtraField4 { get; set; }
        public object ExtraField5 { get; set; }
        public object ShipMonday { get; set; }
        public object ShipMondayLoadDay { get; set; }
        public object ShipTuesday { get; set; }
        public object ShipTuesdayLoadDay { get; set; }
        public object ShipWenesday { get; set; }
        public object ShipWenesdayLoadDay { get; set; }
        public object ShipThursday { get; set; }
        public object ShipThursdayLoadDay { get; set; }
        public object ShipFriday { get; set; }
        public object ShipFridayLoadDay { get; set; }
        public object ShipSaturday { get; set; }
        public object ShipSaturdayLoadDay { get; set; }
        public object ShipSunday { get; set; }
        public object ShipSundayLoadDay { get; set; }
        public object Comment { get; set; }
        public object ContactName { get; set; }
        public object DefaultShipAddress { get; set; }
        public object DropNumber { get; set; }
        public object FulfillLoc { get; set; }
        public object FulfillmentType { get; set; }
        public object PriceAdjustmentPct { get; set; }
        public object RouteCode { get; set; }
        public string ShipZone { get; set; }
        public int? ShipLeadTime { get; set; }
        public object Status { get; set; }
        public object Tax1 { get; set; }
        public object Tax2 { get; set; }
        public object TaxID { get; set; }
        public object TwoStep { get; set; }
        public bool Delete { get; set; }
    }
}
