using System;

namespace B64
{
    public class PlainClient
    {
        public string ClientTaxCode { get; set; }
        public string Vendor { get; set; }
        public string Currency { get; set; }
        public string DefaultSalesRepstring { get; set; }
        public string DefaultShipAddress { get; set; }
        public string Distributor { get; set; }
        public string SalesTerritory { get; set; }
        //public string ClientID { get; set; }
        //public string ID { get; set; }
        public string IntegrationID { get; set; }
        public string IntegrationID2 { get; set; }
        public string IntegrationID3 { get; set; }
        public string DefaultShipAddressID { get; set; }
        public string DefaultShipAddress_IntegrationID { get; set; }
        public string SalesTerritoryID { get; set; }
        public string SalesTerritory_IntegrationID { get; set; }
        public string Currency_IntegrationID { get; set; }
        public string ClientTaxCode_IntegrationID { get; set; }
        public string DistributorID { get; set; }
        public string Distributor_IntegrationID { get; set; }
        public string DefaultSalesRep { get; set; }
        public string DefaultSalesRep_IntegrationID { get; set; }
        public string AutoInvoice { get; set; }
        public string AutoSendInvoice { get; set; }
        public string BillAddress1 { get; set; }
        public string BillAddress2 { get; set; }
        public string BillAddress3 { get; set; }
        public string BillCity { get; set; }
        public string BillCountry { get; set; }
        public string BillCounty { get; set; }
        public string BillFax { get; set; }
        public string BillMobilePhone { get; set; }
        public string BillName { get; set; }
        public string BillPhone { get; set; }
        public string BillState { get; set; }
        public string BillTo { get; set; }
        public string BillZip { get; set; }
        public string ExtraField1 { get; set; }
        public string ExtraField2 { get; set; }
        public string ExtraField3 { get; set; }
        public string ExtraField4 { get; set; }
        public string ExtraField5 { get; set; }
        public string ExtraField6 { get; set; }
        public string ExtraField7 { get; set; }
        public string ExtraField8 { get; set; }
        public string ExtraField9 { get; set; }
        public string ExtraField10 { get; set; }
        public string ExtraField11 { get; set; }
        public string ExtraField12 { get; set; }
        public string ExtraField13 { get; set; }
        public string ExtraField14 { get; set; }
        public string ExtraField15 { get; set; }
        public string ExtraField16 { get; set; }
        public string ExtraField17 { get; set; }
        public string ExtraField18 { get; set; }
        public string ExtraField19 { get; set; }
        public string ExtraField20 { get; set; }
        public string ExtraField21 { get; set; }
        public string ExtraField22 { get; set; }
        public string ExtraField23 { get; set; }
        public string ExtraField24 { get; set; }
        public string ExtraField25 { get; set; }
        public string ExtraFieldLarge { get; set; }
        public string MarkupType { get; set; }
        public string MinMarkupPct { get; set; }
        public string MaxMarkupPct { get; set; }
        public string MinMarkupAmt { get; set; }
        public string MaxMarkupAmt { get; set; }
        public string AllowTwoStepCompanyDiscounts { get; set; }
        public string AutomaticOrderHold { get; set; }
        public string AutomaticOrderHoldDuration { get; set; }
        public string ClientName { get; set; }
        public string ClientTaxCodeID { get; set; }
        public string ClientTerms { get; set; }
        public string Comment { get; set; }
        public string ContactName { get; set; }
        public string CreditBalance { get; set; }
        public string CreditHold { get; set; }
        public string CreditLimit { get; set; }
        public string ClientWarranty { get; set; }
        public string ContractAdjustments { get; set; }
        public string ContractTermsConditions { get; set; }
        public string CreditManagerEmail { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyID { get; set; }
        public string CustomUpcharge { get; set; }
        public string DealerClientType { get; set; }
        public string DefaultHeldItemDeliveryMethod { get; set; }
        public string DefaultRetentionPct { get; set; }
        public string DropNumber { get; set; }
        public string EligibleForExtendedWarranty { get; set; }
        public string Email { get; set; }
        public string EnableAutoGenerateSentQuoteXMLFile { get; set; }
        public string ExtraData { get; set; }
        public string Freight { get; set; }
        public string FulfillmentType { get; set; }
        public string HasCreditLimit { get; set; }
        public string Installation { get; set; }
        public string IntegrationGroup { get; set; }
        public string InvoiceEDIAssembly { get; set; }
        public string InvoiceEDIClass { get; set; }
        public string InvoiceEDIPath { get; set; }
        public string InvoiceMethod { get; set; }
        public string ManufacturerWarranty { get; set; }
        public string NeedsAttention { get; set; }
        public string OrderAckEDIAssembly { get; set; }
        public string OrderAckEDIClass { get; set; }
        public string OrderAckEDIDirectory { get; set; }
        public string OrderAckType { get; set; }
        public string OrderIntegrationAssembly { get; set; }
        public string OrderIntegrationCaption { get; set; }
        public string OrderIntegrationClass { get; set; }
        public string PORequired { get; set; }
        public string PrepayStatus { get; set; }
        public string ProductionPriority { get; set; }
        public string ProposalTermsConditions { get; set; }
        public string QuoteClientMarkupSetupChargePct { get; set; }
        public string ReleaseScreensOption { get; set; }
        public string RequireQuoteVerification { get; set; }
        public string RequiresRetention { get; set; }
        public string RetailExtendedWarranty { get; set; }
        public string RetentionBillDateTimespan { get; set; }
        public string RouteCode { get; set; }
        public string ShipZone { get; set; }
        public string Status { get; set; }
        public string Tax1 { get; set; }
        public string Tax2 { get; set; }
        public string TaxExempt { get; set; }
        public string TaxID { get; set; }
        public string TwoStep { get; set; }
        public string UseCustomerListPriceCodes { get; set; }
        public string UsedForTesting { get; set; }
        public string UseShipToFax { get; set; }
        public string Delete { get; set; }

    }

}

